const transactionData = [
    {
      transactionType: 'Load',
      transportMode: '—',
      entryExit: '—',
      amount: '+₱50.00',
      balance: '₱150.00',
      paraBalance: '10 $PARA',
      tokensEarned: '0 $PARA',
      status: 'Completed',
      timestamp: '2024-06-12 09:01:10',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Bus',
      entryExit: 'Entry',
      amount: '-₱20.00',
      balance: '₱130.00',
      paraBalance: '12 $PARA',
      tokensEarned: '2 $PARA',
      status: 'Completed',
      timestamp: '2024-06-12 08:30:10',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Train',
      entryExit: 'Exit',
      amount: '-₱15.00',
      balance: '₱115.00',
      paraBalance: '14 $PARA',
      tokensEarned: '2 $PARA',
      status: 'Completed',
      timestamp: '2024-06-11 18:45:00',
    },
    {
      transactionType: 'Load',
      transportMode: '—',
      entryExit: '—',
      amount: '+₱100.00',
      balance: '₱200.00',
      paraBalance: '15 $PARA',
      tokensEarned: '0 $PARA',
      status: 'Completed',
      timestamp: '2024-06-10 10:15:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Bus',
      entryExit: 'Exit',
      amount: '-₱30.00',
      balance: '₱170.00',
      paraBalance: '17 $PARA',
      tokensEarned: '2 $PARA',
      status: 'Completed',
      timestamp: '2024-06-10 11:00:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Train',
      entryExit: 'Entry',
      amount: '-₱10.00',
      balance: '₱190.00',
      paraBalance: '18 $PARA',
      tokensEarned: '1 $PARA',
      status: 'Completed',
      timestamp: '2024-06-09 08:00:00',
    },
    {
      transactionType: 'Load',
      transportMode: '—',
      entryExit: '—',
      amount: '+₱75.00',
      balance: '₱275.00',
      paraBalance: '20 $PARA',
      tokensEarned: '0 $PARA',
      status: 'Completed',
      timestamp: '2024-06-08 07:30:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Bus',
      entryExit: 'Entry',
      amount: '-₱25.00',
      balance: '₱250.00',
      paraBalance: '22 $PARA',
      tokensEarned: '2 $PARA',
      status: 'Completed',
      timestamp: '2024-06-07 09:45:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Train',
      entryExit: 'Exit',
      amount: '-₱12.50',
      balance: '₱237.50',
      paraBalance: '23 $PARA',
      tokensEarned: '1 $PARA',
      status: 'Completed',
      timestamp: '2024-06-06 18:15:00',
    },
    {
      transactionType: 'Load',
      transportMode: '—',
      entryExit: '—',
      amount: '+₱60.00',
      balance: '₱297.50',
      paraBalance: '25 $PARA',
      tokensEarned: '0 $PARA',
      status: 'Completed',
      timestamp: '2024-06-05 12:45:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Bus',
      entryExit: 'Exit',
      amount: '-₱18.00',
      balance: '₱279.50',
      paraBalance: '27 $PARA',
      tokensEarned: '2 $PARA',
      status: 'Completed',
      timestamp: '2024-06-04 16:00:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Train',
      entryExit: 'Entry',
      amount: '-₱22.00',
      balance: '₱257.50',
      paraBalance: '28 $PARA',
      tokensEarned: '1 $PARA',
      status: 'Completed',
      timestamp: '2024-06-03 14:30:00',
    },
    {
      transactionType: 'Load',
      transportMode: '—',
      entryExit: '—',
      amount: '+₱80.00',
      balance: '₱337.50',
      paraBalance: '30 $PARA',
      tokensEarned: '0 $PARA',
      status: 'Completed',
      timestamp: '2024-06-02 10:00:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Bus',
      entryExit: 'Exit',
      amount: '-₱35.00',
      balance: '₱302.50',
      paraBalance: '32 $PARA',
      tokensEarned: '2 $PARA',
      status: 'Completed',
      timestamp: '2024-06-01 17:45:00',
    },
    {
      transactionType: 'Payment',
      transportMode: 'Train',
      entryExit: 'Entry',
      amount: '-₱14.00',
      balance: '₱288.50',
      paraBalance: '33 $PARA',
      tokensEarned: '1 $PARA',
      status: 'Completed',
      timestamp: '2024-05-31 20:00:00',
    },
  ];
  
  export default transactionData;
  